### ISSUE TITLE
`causalml` fails to install with conda environment

### ISSUE THREAD

**Issue by joseppinto** [uber/causalml#624]
**Describe the bug**
`causalml` fails to install on a conda environment even with the specified environments in [`envs`](https://github.com/uber/causalml/tree/master/envs).
The issue is similar to the one reported in #321 .

**How to replicate**
I'm using this Dockerfile:
```
FROM python:3.8
# Install conda and put it on the PATH
RUN curl -o /tmp/miniconda_install.sh https://repo.anaconda.com/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh \
    && ([ -f /tmp/miniconda_install.sh ] || (echo "ERROR: Failed to download miniconda_install script"; exit 1)) \
    && bash /tmp/miniconda_install.sh -b -p /miniconda \
    && rm /tmp/miniconda_install.sh
ENV PATH /miniconda/bin:$PATH

COPY req.yaml /req.yaml
RUN conda env update -n base --file /req.yaml
```

Output/Error message: https://pastebin.com/4E5LYy45

And here is the `req.yaml`:
```yaml
channels:
- defaults
- conda-forge
dependencies:
  - python=3.8
  # From https://github.com/uber/causalml/blob/master/envs/environment-py38.yml
  - pip=21.0.1
  - setuptools=52.0.0
  - pip:
    - absl-py==0.12.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.1
    - cffi==1.14.5
    - chardet==4.0.0
    - coverage==5.5
    - cycler==0.10.0
    - cython==0.29.23
    - decorator==5.0.7
    - defusedxml==0.7.1
    - dill==0.3.3
    - entrypoints==0.3
    - future==0.18.2
    - gast==0.3.3
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - h5py==2.10.0
    - idna==2.10
    - iniconfig==1.1.1
    - ipykernel==5.5.3
    - ipython==7.22.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.7.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - kiwisolver==1.3.1
    - lightgbm==3.2.1
    - llvmlite==0.36.0
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.3.0
    - numba==0.53.1
    - numpy==1.23.2
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - patsy==0.5.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - pluggy==0.13.1
    - progressbar2==3.53.1
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - protobuf==3.15.8
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydotplus==2.0.2
    - pygam==0.8.0
    - pygments==2.8.1
    - pyparsing==2.4.7
    - pyro-api==0.1.2
    - pyro-ppl==1.6.0
    - pyrsistent==0.17.3
    - pytest==6.2.3
    - pytest-cov==2.11.1
    - python-dateutil==2.8.1
    - graphviz
    - python-utils==2.5.6
    - pytz==2021.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - qtconsole==5.0.3
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - seaborn==0.11.1
    - send2trash==1.5.0
    - shap==0.37.0
    - six==1.15.0
    - slicer==0.0.3
    - statsmodels==0.12.2
    - termcolor==1.1.0
    - terminado==0.9.4
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.8.1
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wheel==0.36.2
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
    - xgboost==1.4.1
    - causalml>=0.10.0
    # Other dependencies
    - mlflow==1.22.0
    - pyarrow==9.0.0
    - s3fs==2023.6.0
    - gitpython==3.1.31
``` 

**Expected behavior**
`causalml` clean installation

**Environment (please complete the following information):**
 - OS: Mac and Linux
 - Python Version: 3.8
 - Versions of Major Dependencies: as specified in req.yaml
